import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
// import styles from '../styles/Home.module.css'
import LandingPage from './start/LandingPage'
import ChatApp from './start/ChatApp'
import { supabase } from '../utils/supabaseClient'

export default function Home() {
  const user = supabase.auth.user();

  // const [loginCredential, setLoginCredential] = useState([])
  // saveLoginCredential(){
  //   setLoginCredential([])
  // }

  return (
    <>
      <Head>
        <title>Shed Live</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {user ?
        <ChatApp/>:<LandingPage/>
      }
    </>
  )
}
